name: Deploy app

on:
  push:
      branches:
        - main
jobs:
     deploy:
           runs-on: ubuntu-latest

           steps:
             - name: checkout code
               uses: actions/checkout@v2

             - name: deploy app to tomcat
               env:
                  TOMCAT_URL: "https://localhost:8080"
                  TOMCAT_USER: "admin"
                  TOMCAT_PASSWORD: "admin"

               run:
                echo "App deployed"
