name: Deploy app

on:
  push:
      branches:
        - main
jobs:
     deploy:
           runs-on: ubuntu-latest

           steps:
               uses: actions/checkout@v2

             - name: Docker work item title
              run:
                echo "Hello world" > web.html
                python -m http.server 8080
